import { z } from 'zod'

const noTrailingSlash = z.string().url().transform(s => s.replace(/\/+$/, ''))

const schema = z.object({
  NEXT_PUBLIC_API_URL: noTrailingSlash,
  NEXT_PUBLIC_CLOUDFRONT_BASEURL: noTrailingSlash,
  NEXT_PUBLIC_CLOUDFRONT: z.string().min(1),
  NEXT_PUBLIC_AITA_SUBGRAPH: noTrailingSlash,
  NEXT_PUBLIC_HYPERLIQUID_API_URL: noTrailingSlash,
  NEXT_PUBLIC_RPC_URL_ARBITRUM: noTrailingSlash,
  NEXT_PUBLIC_RPC_URL_ARBITRUM_SEPOLIA: noTrailingSlash,
  NEXT_PUBLIC_REOWN_ID: z.string().min(1),
  NEXT_PUBLIC_AGENT_FACTORY: z.string().min(1).optional(),
  NEXT_PUBLIC_AGENT_SPONSOR: z.string().min(1).optional(),
  NEXT_PUBLIC_AGENT_INIT_MARKETCAP: z.string().min(1),
  NEXT_PUBLIC_AGENT_INIT_SUPPLY: z.string().min(1),
  NEXT_PUBLIC_AITA_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_USDC_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_USDC_ARBITRUM_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_WETH_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_WETH_ARBITRUM_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_UNIVERSAL_ROUTER: z.string().min(1).optional(),
  NEXT_PUBLIC_QUOTER_V2_ADDRESS: z.string().min(1).optional(),
  NEXT_PUBLIC_UNISWAP_FACTORY: z.string().min(1).optional(),
  NEXT_PUBLIC_HYPERLIQUID_URL: z.string().min(1).optional(),
  NEXT_PUBLIC_AITA_MORALIS_KEY: z.string().min(1).optional()
})

export const publicEnv = schema.parse({
  NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_CLOUDFRONT_BASEURL: process.env.NEXT_PUBLIC_CLOUDFRONT_BASEURL,
  NEXT_PUBLIC_CLOUDFRONT: process.env.NEXT_PUBLIC_CLOUDFRONT,
  NEXT_PUBLIC_AITA_SUBGRAPH: process.env.NEXT_PUBLIC_AITA_SUBGRAPH,
  NEXT_PUBLIC_HYPERLIQUID_API_URL: process.env.NEXT_PUBLIC_HYPERLIQUID_API_URL,
  NEXT_PUBLIC_RPC_URL_ARBITRUM: process.env.NEXT_PUBLIC_RPC_URL_ARBITRUM,
  NEXT_PUBLIC_RPC_URL_ARBITRUM_SEPOLIA: process.env.NEXT_PUBLIC_RPC_URL_ARBITRUM_SEPOLIA,
  NEXT_PUBLIC_REOWN_ID: process.env.NEXT_PUBLIC_REOWN_ID,
  NEXT_PUBLIC_AGENT_FACTORY: process.env.NEXT_PUBLIC_AGENT_FACTORY,
  NEXT_PUBLIC_AGENT_SPONSOR: process.env.NEXT_PUBLIC_AGENT_SPONSOR,
  NEXT_PUBLIC_AGENT_INIT_MARKETCAP: process.env.NEXT_PUBLIC_AGENT_INIT_MARKETCAP,
  NEXT_PUBLIC_AGENT_INIT_SUPPLY: process.env.NEXT_PUBLIC_AGENT_INIT_SUPPLY,
  NEXT_PUBLIC_AITA_ADDRESS: process.env.NEXT_PUBLIC_AITA_ADDRESS,
  NEXT_PUBLIC_USDC_ADDRESS: process.env.NEXT_PUBLIC_USDC_ADDRESS,
  NEXT_PUBLIC_USDC_ARBITRUM_ADDRESS: process.env.NEXT_PUBLIC_USDC_ARBITRUM_ADDRESS,
  NEXT_PUBLIC_WETH_ADDRESS: process.env.NEXT_PUBLIC_WETH_ADDRESS,
  NEXT_PUBLIC_WETH_ARBITRUM_ADDRESS: process.env.NEXT_PUBLIC_WETH_ARBITRUM_ADDRESS,
  NEXT_PUBLIC_UNIVERSAL_ROUTER: process.env.NEXT_PUBLIC_UNIVERSAL_ROUTER,
  NEXT_PUBLIC_QUOTER_V2_ADDRESS: process.env.NEXT_PUBLIC_QUOTER_V2_ADDRESS,
  NEXT_PUBLIC_UNISWAP_FACTORY: process.env.NEXT_PUBLIC_UNISWAP_FACTORY,
  NEXT_PUBLIC_HYPERLIQUID_URL: process.env.NEXT_PUBLIC_HYPERLIQUID_URL,
  NEXT_PUBLIC_AITA_MORALIS_KEY: process.env.NEXT_PUBLIC_AITA_MORALIS_KEY
})